### ISSUE TITLE
打出不在 Unicode 基础多文本平面（Unicode 点位超过 U+FFFF）的字符时，中间的答案提示显示异常

### ISSUE THREAD

**Issue by 3TUSK** [SkyEye-FAST/minecraft_translation_flask#10]
如下图。

<img width="904" alt="Screen Shot 2024-07-11 at 6 40 04 PM" src="https://github.com/user-attachments/assets/59ef7d70-ce76-49bb-8fb1-2c49efa107de">

随便打点什么「𰻝𰻝面」的「𰻝」（U+30EDD）也可以观察到一样的问题。

Chromium 内核版本 125.0.6422.112。

疑似是强行显示一对 surrogate pair 的结果。估计是什么库没处理对 UTF-16……

**Comment by SkyEye-FAST** [comment]
~~什么风把您吹来了.jpg~~

大概看了一下，这是因为JavaScript中遍历`#inputBox.val()`的时候按每16 bit遍历，而BMP之外的代理对就被硬拆成了两个字符。例如“𰻝”(U+30EDD)，UTF-16中编码为`0xD883 0xDEDD`，这里就会被拆成`0xD883`和`0xDEDD`。

``` js
    $(".box").each(function (index) {
        const $box = $(this);
        const userInput = input[index];
        const correctChar = translation[index];

        $box.text(userInput || "");

        if (!userInput) {
            $box.css("background-color", "#9ca3af25");
        } else if (userInput === correctChar) {
            $box.css("background-color", "#79b851");
        } else if (translation.includes(userInput)) {
            $box.css("background-color", "#f3c237");
        } else {
            $box.css("background-color", "#9ca3af25");
        }
    });
```

实际上简体中文语言文件里没有BMP以外的字符，但是为了防止在酒吧里点炒饭，还是换用`Array.from`修一下罢。

**Comment by SkyEye-FAST** [comment]
现在已经修复了Unihan字符的问题，但是Emoji中还带U+200D没法正常组合……

**Comment by AlPha5130** [comment]
> 现在已经修复了Unihan字符的问题，但是Emoji中还带U+200D没法正常组合……

你需要[`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter)。

**Comment by SkyEye-FAST** [comment]
~~用`Intl.Segmenter`分隔字符后能够正常显示，但是没法输入大型Emoji。~~

破案了，是初始的`maxlength`不够长导致的。事实上现在已经不需要初始设置`maxlength`了。我是唇笔.jpg
