### ISSUE TITLE
测验结算页面的“再来一组”按钮疑似失效

### ISSUE THREAD

**Issue by dovisutu** [SkyEye-FAST/minecraft_translation_flask#11]
环境：Edge 126.0.2592.102

代码分析：
随 c03b0f2 引入main分支，“再来一组”按钮移除了onclick事件绑定，转而绑定到restartButton这一id上，但似乎并未在此id上绑定相应的事件函数，这导致该按钮似乎成为了假按钮。

上述内容按照main分析；暂未查验dev上是否已推送修复。

**Comment by SkyEye-FAST** [comment]
在 c03b0f2 中实际上在`quiz.js`中绑定了事件：

``` js
    $('#restartButton').click(function () {
        window.location.href = `../quiz/${randomCode}`;
    });
```

但是后续由于修 #8 修急眼了，重构代码的时候把这个绑定意外删掉了。

**Comment by SkyEye-FAST** [comment]
Fixed in 363a90a.
