### ISSUE TITLE
译名测试页中，“跳过”按钮的一些奇怪行为

### ISSUE THREAD

**Issue by dovisutu** [SkyEye-FAST/minecraft_translation_flask#17]
译名测试页中，按照设计，在仅剩一处可提示内容时，“提示”将被“跳过”按钮代替。然而，该按钮具有以下行为：
- 按下该按钮时，最后一处提示不会显示提示。
- 结算页面中，最后一处提示不显示为红/蓝色。在暗色模式下，似乎以一种不太确定的方式染色为黑或白色；在亮色模式下，似乎没有问题。
- 在部分填写正确内容时跳过该题将不会计分。

这似乎是因为跳过按钮不会更新提示状态。
（然而，跳过按钮显示时未必有可提示内容：例如，提示部分内容后，填写剩余内容（但不使提示内容正确）将会显示跳过按钮，但没有可提示内容。）

其实我感觉”跳过“本身的设计就有点怪：除了跳过以外的其他操作都需要填完正确内容才能进入下一题，但跳过是强制进下一题。结合提完最后一处强制跳过的”特性“，这导致需要提示末尾几个字的题目体验较差。

**Comment by SkyEye-FAST** [comment]
Works as Intended.
如果有需要，请去 #16 补充你的想法。
原本提示和跳过是并存的，但是在反馈下才改成了现在的情况。
