### ISSUE TITLE
资源获取慢

### ISSUE THREAD

**Issue by YaoSiQian** [SkyEye-FAST/minecraft_translation_flask#4]
# 问题
字体文件太大，而资源文件位于 Vercel CDN 上，导致加载速度缓慢。
![image](https://github.com/SkyEye-FAST/minecraft_translation_flask/assets/29835749/4c4a59bd-8a95-41d8-918a-ef4de9fb60ca)

# 可能可以的解决方案
- [Google Fonts](https://fonts.google.com/noto/specimen/Noto+Serif+SC)
- jsDeliver 或其他加速链接方案来直接获取 GitHub 资源库上的字体文件
- ~换字体~

**Comment by SkyEye-FAST** [comment]
我建议是本地装一份思源宋体（为什么有人2024年了还没有装思源宋体.jpg）

1. Google Fonts国内不稳定，可能用Adobe的源会好一点？
2. 静态文件也是Vercel构建的，难说
3. 也许能和一点明体一样自动构建子集，但是没什么必要

**Comment by SkyEye-FAST** [comment]
已换用Google Fonts国内源
